---
- name: clean opensds flexvolume plugins binary file
  file:
    path: "{{ flexvolume_plugin_dir }}"
    state: absent
    force: yes
  ignore_errors: yes
  when: nbp_plugin_type == "flexvolume"

- name: clean nbp release files
  file:
    path: "{{ nbp_dir }}"
    state: absent
    force: yes
  ignore_errors: yes

- name: clean nbp release tarball file
  file:
    path: "{{ nbp_tarball_url }}"
    state: absent
    force: yes
  ignore_errors: yes
