---
- name: run osdslet daemon service
  shell:
    cmd: |
      i=0
      while
        i="$((i+1))"
        [ "$i" -lt 4 ]
      do
        nohup bin/osdslet > osdslet.out 2> osdslet.err < /dev/null &
        sleep 5
        ps aux | grep osdslet | grep -v grep && break
      done
  args:
    chdir: "{{ opensds_build_dir }}/out"
  when: container_enabled == false

- name: run osdslet containerized service
  docker:
    name: osdslet
    image: opensdsio/opensds-controller:latest
    state: started
    net: host
    volumes:
    - "/etc/opensds/:/etc/opensds"
  when: container_enabled == true
