---
# Defines some clean processes when banishing the cluster.

- name: destory an opensds cluster
  hosts: all
  remote_user: root
  vars_files:
    - group_vars/common.yml
    - group_vars/osdsdb.yml
    - group_vars/osdsdock.yml
  gather_facts: false
  become: True
  roles:
    - cleaner