---
# Defines deployment design and assigns role to server groups

- name: deploy an opensds local cluster
  hosts: all
  remote_user: root
  vars_files:
    - group_vars/common.yml
    - group_vars/osdsdb.yml
    - group_vars/osdslet.yml
    - group_vars/osdsdock.yml
  gather_facts: false
  become: True
  roles:
    - common
    - osdsdb
    - osdslet
    - osdsdock
