---

### In Ubuntu, Debian
- name: Install the spdk dependency packages
  raw: sudo apt-get install -y gcc g++ make libcunit1-dev libaio-dev libssl-dev \
       git astyle pep8 lcov clang uuid-dev
  when:
    - system_version == 'Ubuntu' or system_version == 'Debian'

- name: Install additional dependencies for NVMe over Fabrics
  raw: sudo apt-get install -y libibverbs-dev librdmacm-dev
  when:
    - system_version == 'Ubuntu' or system_version == 'Debian'

- name: Install additional dependencies for DPDK in
  raw: sudo apt-get install -y libnuma-dev
  when:
    - system_version == 'Ubuntu' or system_version == 'Debian'

- name: Install additional dependencies for building docs
  raw: sudo apt-get install -y doxygen mscgen
  when:
    - system_version == 'Ubuntu' or system_version == 'Debian'


### In Centos, Fedora
- name: Install the package 'epel-release' for Centos
  raw: sudo yum --enablerepo=extras install -y epel-release
  when:
    - system_version == 'Centos'

- name: Install the spdk dependency packages in Centos, Fedora
  raw: sudo yum install -y gcc gcc-c++ make CUnit-devel libaio-devel openssl-devel \
       git astyle-devel python-pep8 lcov python clang-analyzer libuuid-devel
  when:
    - system_version == 'Centos' or system_version == 'Fedora'

- name: Install additional dependencies for NVMe over Fabrics in ubuntu, Debian
  raw: sudo yum install -y libibverbs-devel librdmacm-devel
  when:
    - system_version == 'Centos' or system_version == 'Fedora'

- name: Install additional dependencies for DPDK in ubuntu, Debian
  raw: sudo yum install -y numactl-devel
  when:
    - system_version == 'Centos' or system_version == 'Fedora'

- name: Install additional dependencies for building docs in ubuntu, Debian
  raw: sudo yum install -y doxygen mscgen
  when:
    - system_version == 'Centos' or system_version == 'Fedora'

### In FreeBSD
- name: Install the spdk dependency packages
  raw: sudo pkg install gmake cunit openssl git devel/astyle bash devel/pep8 \
       python misc/e2fsprogs-libuuid
  when:
    - system_version == 'FreeBSD'

- name: Install additional dependencies for building docs
  raw: sudo pkg install doxygen mscgen
  when:
    - system_version == 'FreeBSD'