---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: check for nbp release files existed
  stat:
    path: "{{ nbp_dir }}"
  ignore_errors: yes
  register: releasesexisted

- name: download nbp release files
  get_url:
    url={{ nbp_download_url }}
    dest={{ nbp_tarball_url }}
  when:
    - releasesexisted.stat.exists is undefined or releasesexisted.stat.exists == false

- name: extract the nbp release tarball
  unarchive:
    src={{ nbp_tarball_url }}
    dest=/opt/
  when:
    - releasesexisted.stat.exists is undefined or releasesexisted.stat.exists == false
