---
# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:


###########
# GENERAL #
###########

db_driver: etcd
db_endpoint: localhost:2379,localhost:2380
#db_credential: opensds:password@127.0.0.1:3306/dbname

###########
#  ETCD   #
###########

etcd_release: v3.2.0
etcd_host: 127.0.0.1
etcd_port: 2379
etcd_peer_port: 2380

# These fields are not suggested to be modified
etcd_tarball: etcd-{{ etcd_release }}-linux-amd64.tar.gz
etcd_download_url: https://github.com/coreos/etcd/releases/download/{{ etcd_release }}/{{ etcd_tarball }}
etcd_dir: /opt/etcd-{{ etcd_release }}-linux-amd64

###########
# DOCKER  #
###########

etcd_docker_image: quay.io/coreos/etcd:latest
