---
# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:


###########
# GENERAL #
###########

# These fields are NOT suggested to be modified
controller_endpoint: 0.0.0.0:50040
controller_log_file: "{{ opensds_log_dir }}/osdslet.log"

###########
# DOCKER  #
###########

controller_docker_image: opensdsio/opensds-controller:latest
