# Copyright (c) 2018 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: check for nbp release files existed
  stat:
    path: "{{ nbp_tarball_dir }}"
  ignore_errors: yes
  register: nbpreleasesexisted

- name: download and extract the nbp release tarball if not exists
  unarchive:
    src={{ nbp_download_url }}
    dest=/tmp/
  when:
    - nbpreleasesexisted.stat.exists is undefined or nbpreleasesexisted.stat.exists == false

- name: change the mode of all binary files in nbp release
  file:
    path: "{{ nbp_tarball_dir }}/flexvolume"
    mode: 0755
    recurse: yes

- name: copy nbp tarball into nbp work directory
  copy:
    src: "{{ nbp_tarball_dir }}/"
    dest: "{{ nbp_work_dir }}"
